roles/linux-executor/tasks/prep_system.yml
Fixed openfiles.conf to add the '*'
=> fixed openfiles.conf

roles/linux-executor/tasks/circleci_specific.yml
=> Configure ssh, iptables and keys

playbooks/linux/linux_configure_vars.yml, roles/linux-executor/defaults/main/system_defaults.yml, roles/linux-executor/tasks/install_java.yml, roles/linux-executor/tasks/main.yml
=> install java

roles/linux-executor/tasks/install_jq.yml, roles/linux-executor/tasks/install_yq.yml, roles/linux-executor/tasks/main.yml
Installing jq. Need to talk to @felicianotech about yq because I am getting errors that the package can not be found
=> Install jq

roles/linux-executor/defaults/main/install_python_vars.yml, roles/linux-executor/tasks/install_python.yml, roles/linux-executor/tasks/main.yml
main.yml has tasks commented out to make builds faster during my testing. They will be uncommented once I have completed all build components.
=> install python

roles/linux-executor/defaults/main/install_nodejs_vars.yml, roles/linux-executor/tasks/install_nodejs.yml, roles/linux-executor/tasks/main.yml
tasks commented out in main.yml to shorten builds while im testing. I will uncomment these tasks once I am complete with the rewrite
=> install nodejs and nvm

roles/linux-executor/defaults/main/install_docker_vars.yml, roles/linux-executor/tasks/install_docker.yml, roles/linux-executor/tasks/main.yml
eventually put the version numbers back
=> Install docker and  docker compose

roles/linux-executor/defaults/main/install_chrome_vars.yml, roles/linux-executor/tasks/circleci_specific.yml, roles/linux-executor/tasks/configure_dpkg.yml, roles/linux-executor/tasks/install_python.yml, roles/linux-executor/tasks/main.yml, roles/linux-executor/tasks/prep_system.yml
linux build work completed. ready for handoff to @felicianotech and @JalexChen 
pyenv still needed a full path no matter what i tried. 
code cleaned up and all tasks uncommented in main.yml
=> cleanup,config dpkg, uncomment all tasks

roles/linux-executor/defaults/main/install_chrome_vars.yml, roles/linux-executor/defaults/main/install_firefox_vars.yml, roles/linux-executor/tasks/install_chrome.yml, roles/linux-executor/tasks/install_firefox.yml
update chrome and firefox downloads to "latest" instead of a pinned version
=> Firefox change

roles/linux-executor/defaults/main/install_docker_vars.yml, roles/linux-executor/defaults/main/install_gcloud_vars.yml, roles/linux-executor/defaults/main/install_golang_vars.yml, roles/linux-executor/defaults/main/install_gradle_vars.yml, roles/linux-executor/defaults/main/install_nodejs_vars.yml, roles/linux-executor/defaults/main/install_python_vars.yml, roles/linux-executor/defaults/main/install_yarn_vars.yml
updates versions to match the current 22.04 provisioner. once the build is successfully completed, we can merge this in
=> match provisioner versions

playbooks/linux/hosts, playbooks/linux/linux_configure.yml, playbooks/linux/linux_configure_vars.yml, roles/linux-executor/tasks/circleci_specific.yml, roles/linux-executor/tasks/create_users.yml, roles/linux-executor/tasks/main.yml, roles/linux-executor/tasks/prep_system.yml
this is not complete. this will create most things and the commented out parts require a new version of ansible. however, these attributes already exist; commented out config would simply check for the presence.
tasks are commented out as i'll be going through them one by one in subsequent updates
=> feat: add os1 and os2 script as ansible

roles/linux-executor/tasks/install_gcloud.yml
i believe i added this step in for testing purposes. this should be removed
=> fix: removes extra  circleci gcloud config step

roles/linux-executor/tasks/install_golang.yml, roles/linux-executor/tasks/install_maven.yml, roles/linux-executor/tasks/install_nodejs.yml, roles/linux-executor/tasks/install_python.yml, roles/linux-executor/tasks/install_ruby.yml
using blockinfile for the same file e.g circlerc will overwrite due to the default # ANSIBLE MANAGED marker
=> feat: add markers to prevent overwriting

roles/linux-executor/tasks/install_ruby.yml
=> fix: pathing for ruby

roles/linux-executor/tasks/install_nodejs.yml
- removes heredoc
- change permissions on nvm_dir
=> fix: remove heredoc and add perms to nvm_dir

roles/windows-executor/defaults/main/install_buildagent_prereq_defaults.yml, roles/windows-executor/defaults/main/install_cloud_tools_defaults.yml, roles/windows-executor/defaults/main/install_dev_tools_defaults.yml, roles/windows-executor/defaults/main/install_microsoft_tools_defaults.yml
Updated the following packages:
sysinternals
awscli
service fabric sdk
vim
openjdk
docker engine
.NET SDK
Visual Studio 2022 Community Edition
VIsual Studio 2022 Community Edition build tools
=> windows: win server 2022 october package updates

roles/system_prep/tasks/main.yml, roles/system_prep/vars/main.yml
- adds fcqa for modules
- granular file and directory permissions
=>  refactor: add new role for system_prep

roles/base/files/apt.conf, roles/base/tasks/main.yml, roles/base/vars/main.yml
=> add base role

roles/ant/tasks/main.yml, roles/ant/vars/main.yml, roles/devtools/tasks/main.yml, roles/devtools/vars/main.yml, roles/jq/tasks/main.yml, roles/jq/vars/main.yml, roles/nsenter/tasks/main.yml, roles/nsenter/vars/main.yml, roles/socat/tasks/main.yml, roles/socat/vars/main.yml, roles/sysadmin_tools/tasks/main.yml, roles/sysadmin_tools/vars/main.yml, roles/yq/tasks/main.yml, roles/yq/vars/main.yml
there is a variable {{ arch }} that is currently being used here, however, there is no mechanism for this. this will be added as a global task to minimize repitition
=> add misc tool roles

roles/java/tasks/main.yml, roles/java/vars/main.yml
this PR also requires the global task of designating the {{ arch }} variable
=> adds java role

roles/awscli/tasks/main.yml, roles/awscli/vars/main.yml, roles/gcloud/tasks/main.yml, roles/gcloud/vars/main.yml
the current way to find the architecture is not ideal and needs to be made a bit more dynamic.
perhaps .j2 templating, but the `when` conditional does not support this
=> add cloud cli roles

roles/golang/tasks/main.yml, roles/golang/vars/main.yml
this is also a role that will require the arch variable
=> add golang role

roles/java/tasks/main.yml, roles/java/vars/main.yml
maven and gradle were initially left out of this as they had their own tasks. this is now included into one
=>  initial maven + gradle install within java

roles/python3/library/pyenv.py, roles/python3/tasks/main.yml, roles/python3/vars/main.yml
Uses a custom ansible module to install pyenv
=> add pyenv with modules commit

roles/ruby/library/rbenv.py, roles/ruby/tasks/main.yml
Uses a custom rbenv ansible module to install rbenv
=> add rbenv with module

playbooks/linux/linux_configure.yml, roles/awscli/tasks/main.yml, roles/base/tasks/main.yml, roles/cci_specific/tasks/main.yml, roles/chrome/tasks/main.yml, roles/firefox/tasks/main.yml, roles/java/tasks/main.yml, roles/scala/tasks/main.yml, roles/yq/tasks/main.yml
- Tidy up the repo to make it a bit more consistent in terms of syntax and naming
- Moves roles with higher coefficients of error to induce failing faster
=> refactor: tidy

manifest/software.json, tests/conftest.py, tests/test_base_role.py, tests/test_manifest.py, tests/test_system_prep.py
- adds a conftest.py to persist some variables and configure pytest
- adds tests for the base role
- adds tests for the manifest
- adds tests for the system_prep_role
- updates software manifest
=> feat: add tests for module

roles/windows-executor/defaults/main/install_buildagent_prereq_defaults.yml, roles/windows-executor/defaults/main/install_cloud_tools_defaults.yml, roles/windows-executor/defaults/main/install_dev_tools_defaults.yml, roles/windows-executor/defaults/main/install_microsoft_tools_defaults.yml
Software bumps for Windows Server 2022 May 2023 release
=> Windows Server 2022 May 2023

manifest/windows-software.json, roles/windows/devtools/tasks/main.yml
Closes CircleCI-Public/windows-orb/issues/42
=> Add rust to Windows Server 2022

.circleci/config.yml, linux-playbook.yml, packer/packer.pkr.hcl, roles/syft/files/sbom, roles/syft/tasks/main.yml, roles/syft/vars/main.yml
- creates SBOM role
- SBOM is included within the image
- `sbom parse` command also added with package string match, exact/all matches, and the option to specify a spdx manifest path
=> feat: generate SBOM role

.circleci/config.yml, roles/syft/files/sbom, roles/syft/tasks/main.yml
- can generate sbom for spdx format, apt, and android
- refactors syft role
=> feat: add to sbom functionality

.circleci/config.yml, manifest/software.json
CI step was skipped as it was rebasing a build that already ran
=> build: software update for q3 jammy amd64

.circleci/config.yml, manifest/windows-software.json, roles/syft/files/sbom, roles/windows/syft/tasks/main.yml, windows-playbook.yml
- add choco and programdata sbom
- add syft role for windows specifically
- sbom parser will need to be moved to a separate location eventually.
=> feat: windows and choco sbom. win sbom role

roles/windows/microsoft_tools/tasks/main.yml
Quick one line change on the conditional for adding visual studio 2022 to path
=> fix: fixed incorrect conditional

manifest/docker23.json, remote_docker-playbook.yml
=> feat: remote-docker 23 build [skip ci]

roles/windows/install_cloudtools/files/install_servicefabric_sdk.ps1, roles/windows/install_cloudtools/tasks/main.yml
fixes service fabric installation by referencing correct args
=> update service fabric installation

android-playbook.yml, manifest/android-test.json, roles/android/tasks/main.yml, roles/android/vars/main.yml, roles/android_tools/tasks/main.yml, roles/android_tools/vars/main.yml
Adds an android playbook and tasks for building the android machine image. This is a part of the push for automating image creation.
=> [IMG-139] feat: android builds
