CircleCI-Public/ansible

roles/windows-executor/defaults/main/install_buildagent_prereq_defaults.yml, roles/windows-executor/defaults/main/install_cloud_tools_defaults.yml, roles/windows-executor/defaults/main/install_dev_tools_defaults.yml, roles/windows-executor/defaults/main/install_microsoft_tools_defaults.yml, roles/windows-executor/tasks/install_dev_tools.yml
OS updates as well as
updated the following packages:
- git
- gitlfs
- sysinternals
- awscli
- azurecli
- nunit 
- vim
- golang
- openjdk
- miniconda3
- python2
- python3
- nodejs
- ruby
- docker-engine
- nvm
- .net sdk
- visual studio community edition
- nuget cli
fix:
remove nodejs directory due to conflict with nvm:
https://discuss.circleci.com/t/march-2022-beta-support-for-new-operating-system-for-windows-executors-windows-server-2022/43198/36
=> maint: june 1 windows server 2022 release. fix nvm

roles/windows-executor/files/disable_default_winservices.ps1
Windows Server 2022 requires 2 modifications to registry to disable UAC. WIndows Server 2019 requires 1 key to be modified. This fix will apply the second requires registry change to windows server 2022.
=> Windows july edge uac fix

roles/windows-executor/defaults/main/install_buildagent_prereq_defaults.yml
Using git 2.37.3 because git 2.37.1 is no longer available
=> win: use git 2.37.3

roles/windows-executor/tasks/install_buildagent_prereq.yml
Setting force to yes because the build is saying git is already installed at a lesser version.
=> windows: set git force to yes

roles/linux-executor/tasks/install_gradle.yml
basically resets the PATH, making several modules unavailable
=> fix: gradle path was escaping the $

roles/windows-executor/files/install_servicefabric_sdk.ps1, roles/windows-executor/tasks/disable_windows_services.yml, roles/windows-executor/tasks/install_dev_tools.yml
removed hyper-v enabling and docker desktop. Need to check with legal team to see if we can include docker desktop and need more time for testing changes of this magnitude. Will revisit for October release assuming there is no legal issues with doing so.
=> windows: removed hyper-v and docker desktop

roles/linux-executor/defaults/main/install_ruby_vars.yml, roles/linux-executor/tasks/install_ruby.yml
ruby was not available when checking the version and was due to being installed on root rather than locally for the circleci user. this installs it using the cci user
=> fix: ruby install

roles/linux-executor/tasks/install_firefox.yml
removes the old pinning way of downloading the focal version of firefox. Since jammy moved to using snap as the download/package manager we now need to set pin priorities. This removes the snap version and installs an apt/.deb version of firefox that the mozilla team maintains.
=> feat: download + install .deb firefox

roles/linux-executor/tasks/create_users.yml
the shorthand version of the `user` module was breaking lint. it is also safer to use the FQCN here in case there are conflicts with other moduls
=> fix: use FQCN user module

roles/linux-executor/tasks/prep_system.yml
AWS security functions a bit differently from GCP, which doesn't allow reading from temp directories. setfacl, included as part of the acl package fixes this
=> fix: acl package is needed for temp directory reads

roles/linux-executor/tasks/install_ruby.yml
there was lag when the canary images did not update, resulting in a change to the ruby path when trying to fix when in fact these permissions are what correctly configure the image.
there is currently no .config included so that's why checks are failing
=> fix: revert rbenv due to lag in image update when testing

roles/linux-executor/defaults/main/install_python_vars.yml, roles/linux-executor/tasks/install_python.yml
when setting global versions for pyenv similar to machine-executor-images, the in-line addition of both versions would actually make both versions (2.7.18 and 3.10.5) global, however, the 2.7.18 version would take precedence, which is not the desired outcome. using a loop would set both as global versions available, but only the second one would be the default
=> fix: make only one global version default, but all available

playbooks/linux/linux_configure.yml, playbooks/linux/linux_configure_vars.yml
Instead of the original linux_configure file, we are now going to modularize the process using roles and use playbooks as intended - as an overarching configuration file to oversee which roles will be installed for a specific installation.
In this use case, this specific linux_configure build would create an amd64 image for linux ubuntu 22.04. An example of how this would be helpful is to specify an additional playbook for linux_configure_arm64, or linux_configure_android, with the key differences being architecture or additional packages for android.
In the case of amd64 vs arm64, it may not be known the incompatibilities, and therefore it may be worth having separate playbooks, however, the easier way is to use dpkg --print-architecture to download the correct packages for each image
=> refactor: add new linux_configure config file

roles/firefox/tasks/main.yml
Since this only really affects 22.04, there may be two roles or a conditional when building for 20.04
=> refactor: adds firefox role

roles/chrome/tasks/main.yml
- this is also a PR that will require an {{ arch }} variable filled in.
- additionally, this will also need to be taken out for arm, as chrome does not have a separate download for that architecture
=> add chrome role

roles/awscli/tasks/main.yml, roles/chrome/tasks/main.yml, roles/gcloud/tasks/main.yml, roles/system_prep/tasks/main.yml
This PR: 
- Uses the system_prep role to register the architecture of the host machine when building
- Refactors logic used for various downloads that are dependent on arm/amd/x86_64 differentiators in their download links
- the java and yq roles now have access to the {{ arch }} variable. golang in PR #126 will also have it once merged
- the chrome role is now only activated when the architecture is x86_64/amd64 since they do not have a separate download link for arm, consistent with the current build process
=> refactor: add registered variable and refactor architecture variable usage

manifest/software.json
adds a manifest that can be invoked with extra args in the command line when running ansible-playbook and allows for easier parsing when tracking the manifest
While this specific repo does not have a packer.json/yaml, this is technically part of the machine-executor flow. However, one can be included at a later date with correct credentials
=> adds manifest

roles/docker/tasks/main.yml
the allow_change_held_packages flag should technically be available in the ansible version being used, but is not. there does not seem to be any conflicts, so removing it.
=> fix: docker flag

roles/base/tasks/main.yml
there is no need to have this step as the apt modules in subsequent steps will update/upgrade. this actually occasionally kills the build
=> refactor: remove apt update in base; not needed

roles/system_prep/tasks/main.yml
removed conditional as this role will be working off a blank image in the first place where these users and groups should not exist in the first place.
- this may need to be edited when the canaries are being built. i cannot check it right now
- added a ' ' for the password, since this is the only way the password is disabled (vs '!' or '*') in ansible docs.
=> refactor: remove conditionals for user and group checking

roles/scala/tasks/main.yml, roles/scala/vars/main.yml
sbt -V creates folders that we do not want or need. additionally, it interferes with the circleci build process due to the project folder.
=> feat: add step to remove sbt created folders

group_vars/linux_configure_vars.yml, linux-playbook.yml, roles/common/tasks/cci_specific.yml, roles/common/tasks/system_prep.yml
Adds ansible_remote_tmp and change mode of .ssh to 0600 to accommodate AWS builds
Removes file reference at the top for linux-playbook
adds user state to present in case the user already exists
Comments out BASH_ENV sourcing for testing
=> refactor: .ssh mode change, add ansible tmp dir, file references

roles/common/tasks/cci_specific.yml, roles/common/tasks/system_prep.yml, roles/golang/tasks/main.yml, roles/node/tasks/main.yml, roles/python3/tasks/main.yml, roles/ruby/tasks/main.yml, roles/scala/tasks/main.yml
the checkout step was failing with the error: `failed to write known_hosts entry: open /home/circleci/.ssh/known_hosts: permission denied` [here](https://app.circleci.com/pipelines/github/circleci/machine-executor-images/4379/workflows/aaf32817-77f8-4752-95ad-31e9a4db47cc/jobs/79396)
as a result, i used an existing image to match the modes across a couple of files. the 600 mode was intended for key files, rather than the directory itself
The `safe directory` for global git config was placed under the NVM download and needed to be moved up
=> chore: add folder mode changes; move safe-directory up a step

roles/windows-executor/defaults/main/install_microsoft_tools_defaults.yml, roles/windows-executor/tasks/install_microsoft_tools.yml
remove .net 7 sdk due to install installing side-by-side with .net 6 sdk. 
Chocolatey no longer supports side-by-side installations.
https://docs.chocolatey.org/en-us/choco/commands/install
Will look into installing .net 7 sdk and .net 6 sdk outside of chocolatey in a future release
=> windows: removed .net 7 sdk

roles/windows-executor/defaults/main/install_cloud_tools_defaults.yml, roles/windows-executor/defaults/main/install_dev_tools_defaults.yml, roles/windows-executor/defaults/main/install_microsoft_tools_defaults.yml
The February image is going to be skipped (#169) so we're diving straight into March.
=> Windows: Server 2022 March 2023 updates

manifest/software.json
because there are incompatibilities with the new Docker version 23, we need to revert back to 20.10.24
=> chore: revert docker version to 20

.circleci/config.yml, linux-playbook.yml, packer/packer.pkr.hcl, packer/variables.pkr.hcl
This adds the minimum viable configuration for building an image on GCP.
notes:
- the aws source will need to be added eventually
- additional builds and a parameter to specify them, along with extra vars will also need to be included
- once the machine-provisioner PR to validate images in`circleci-images`, tests can also be written in
- additional image families for 20.04, android, and edge will also be added pending the machine-provisioner PR
=> chore: add minimum viable packer build and config

.circleci/config.yml, packer/packer.pkr.hcl, packer/variables.pkr.hcl
Closes #191 
Builds were running due to:
- no changes
- checking a directory rather than a specific manifest
- inadequate conditionals
This adds branch pattern matching and the option to skip image creation for test builds
=> refactor: improve build configuration conditionals

roles/system_prep/tasks/main.yml
this used to be an issue, but was flaky when popping up. with this change, we should be able to associate the original uid, which exists as an aws/gcp uid/user to the circleci user
=> fix: flaky uid error

roles/syft/tasks/main.yml
the encompassing quotes were reading that line as one command.
the quotes are now added only around the variables
=> fix quotes

roles/common/tasks/system_prep.yml
#200 fixed the issue, but was in the wrong directory.
the common role should refer to the right directory or simply include the tasks within the directory
=> fix the correct directory

.circleci/config.yml, linux-playbook-test.yml, roles/common/tasks/system_prep.yml
uid clashing kills the build process, as the user being created is already in use.
an image was created with the same manifest using this [build](https://app.circleci.com/pipelines/github/CircleCI-Public/ansible/295/workflows/1b2e1ce2-1057-452b-8397-eca63976ed6a), but would start to fail in subsequent builds.
this [build](https://app.circleci.com/pipelines/github/CircleCI-Public/ansible/304/workflows/06d74c49-492b-40b6-b740-97723db10a8f) confirms we are able to rebuild without encountering a similar error
because gcp and aws have different default users, this accounts for both and only removes a user if the uid being replaced is not circleci, then sets the appropriate groups
=> fix: uid process clashing crashes build

roles/syft/files/sbom, roles/syft/tasks/main.yml
- creates an sbom folder as a separate step and sets permissions for the circleci user
- removes sudo from the script, which unblocks windows
-- removing sudo should also alleviate some file permission access issues
- fixes positional parameters for image name and image tag classifications
=> refactor: remove sudo and add directory perms

roles/common/tasks/system_prep.yml
- changes in behavior for sudo [here](https://www.suse.com/support/kb/doc/?id=000020902) made it so the core dump size was set to 0. this PR fixes it by setting the option to it's defaults
=> fix ulimit defaults

roles/python3/tasks/main.yml
just switching the order of the `pyenv global` command so that python 3+ is the default rather than python 2
=> [PROV-438] fix default python versions

roles/android_tools/tasks/main.yml
fastlane has been broken in trying to install it on recent builds for android changing to this seems to have fixed the issue and tests seem to validate with this change that it is working again. Tested this out through: https://app.circleci.com/pipelines/github/CircleCI-Public/android-machine/165/workflows/4ea53ec8-c1d0-40ff-a120-ccb84913fcf0/jobs/920
https://github.com/CircleCI-Public/android-machine/commit/f944ae664137a5bff0596e0503d98067a00cc763
=> fix fastlane for android

roles/windows/devtools/tasks/main.yml
This helps the Windows machines build for a reason that is quite beyond my understanding.
=> Yank python up the list of dependencies

.circleci/config.yml, packer/packer.pkr.hcl, roles/common/tasks/base.yml
* force packer `ansible` plugin >= `1.1.1` to fix SSH unquoting problems
=> Do not install git ppa for 24.04

roles/windows/microsoft_tools/tasks/main.yml, roles/windows/windows_updates/tasks/main.yml
Corrected issues with `Windows-2019-Machine` build ([example](https://app.circleci.com/pipelines/github/CircleCI-Public/Win-2019-Machine/415/workflows/6cfc224c-b213-485e-a1a5-610086b687bd/jobs/1148)).
=> Reject kb 2267602

roles/windows/nvidia/tasks/main.yml, roles/windows/nvidia/vars/main.yml, windows-nvidia-playbook.yml
Add NVIDIA GPU support for Windows machines
This will help with the new `windows-2022-nvidia-medium` builds
=> Add Windows NVIDIA support role and playbook

roles/windows/nvidia/vars/main.yml
Set default cuda version to `12.8.0.571` since 12.7 is not available. Note: Cuda gets overriden in the WIn-2022 image
=> Update default cuda version for  Windows 2022 Nvidia Image

roles/java/tasks/main.yml
This `http://apache.osuosl.org/maven/maven-3/{{maven_version}}/binaries/apache-maven-{{maven_version}}-bin.tar.gz` is no longer a reliable source, https://osuosl.org/blog/osl-future/
Maven download is now made via the official distribution via `https://archive.apache.org`
=> Update maven download source

roles/common/tasks/system_prep.yml
Fixed Ansible playbook failure by adding a conditional check before modifying the circleci user account, preventing the "user currently used by process" error that occurred when the playbook tried to modify the same user that was running it.
=> Fix user modification error in system prep

roles/windows/microsoft_tools/tasks/main.yml
`IncrediBuild` is being automatically installed as part of Visual Studio workloads in our Windows Server 2022 images. This tool starts a service that binds to port 8000, causing conflicts when customers try to run applications on the same port. This results in bind errors and prevents applications from starting.
Visual Studio installations use --allWorkloads --includeRecommended --includeOptional which includes all available components, including `IncrediBuild`. The `Microsoft.VisualStudio.Component.IncrediBuild` component is installed by default and automatically starts services that use port 8000.
Modified Visual Studio installation parameters in `roles/windows/microsoft_tools/tasks/main.yml` to explicitly exclude the IncrediBuild component.
=> Remove IncrediBuild installation for windows machines
